on:
  milestone:
    types: [closed]
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
      - name: Set release notes
        id: generate
        run: |
          echo ::set-output name=release_notes::`cat temp_release_notes/*`
          echo ::set-output name=date::$(date +'%Y%m%d')
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate.outputs.date }}
          release_name: Release ${{ steps.generate.outputs.date }}
          body: ${{ steps.generate.outputs.release_notes }}
          draft: false
          prerelease: false