name: New issues reminder
on:
  schedule:
    # Run every day at 9am UTC
    #- cron: '15 9 * * *'
    - cron: '*/5 * * * *'
jobs:
  send_reminder:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send a reminder
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const options = github.issues.listForRepo.endpoint.merge({
              state: 'open',
              assignee: none
            });
            github.issues.paginate(option).then(async (issues) => {
              for (const issue of opened_issues) {
                 const message = 'Hey! This issue should be assigned!';
                 await github.issues.createComment({
                                issue_number: issue.number,
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                body: message
                              });
              }
            });

