name: Contributors welcome
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  comment:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Welcome ${{github.actor}} and thank you for your contribution!'
